apiVersion: batch/v1
kind: CronJob
metadata:
  name: feedserver-jobs-digests
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            parent: feedserver-jobs
        spec:
          containers:
          - command:
            - java
            - -jar
            - -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
            - feedserver-jobs-digests.jar
            env:
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  key: API-KEY
                  name: sendgrid
            - name: FEEDSERVER_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: MONGODB_USERNAME
                  name: feedserver-mongodb
            - name: FEEDSERVER_MONGODB_PORT
              valueFrom:
                secretKeyRef:
                  key: MONGODB_PORT
                  name: feedserver-mongodb
            - name: FEEDSERVER_MONGODB_HOST
              valueFrom:
                secretKeyRef:
                  key: MONGODB_HOST
                  name: feedserver-mongodb
            - name: FEEDSERVER_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGODB_PASSWORD
                  name: feedserver-mongodb
            - name: FEEDSERVER_MONGODB_DBNAME
              valueFrom:
                secretKeyRef:
                  key: MONGODB_DBNAME
                  name: feedserver-mongodb
            - name: KEYCLOAK_USERNAME
              valueFrom:
                secretKeyRef:
                  key: saas_serveruser_username
                  name: keycloak-internal
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: saas_serveruser_password
                  name: keycloak-internal
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: saas_serveruser_client_id
                  name: keycloak-internal
            - name: KEYCLOAK_URL
              valueFrom:
                secretKeyRef:
                  key: KC_AUTH_SERVER_URL
                  name: keycloak
            - name: KEYCLOAK_REALM
              valueFrom:
                secretKeyRef:
                  key: KC_REALM
                  name: keycloak
            envFrom:
            - secretRef:
                name: feedserver-jobsboard-config
            image: quay.io/gamerefinery/feedserver-jobs
            imagePullPolicy: Always
            name: feedserver-jobs-digests
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          imagePullSecrets:
          - name: quay-puller
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 0 0 * * *
  successfulJobsHistoryLimit: 1
  suspend: false