name: PR to main

on:
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  compile:
    name: Ping
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get commit SHA
      id: commit_id
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Getbranch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: branch_name

    # If none of these files has changed, we assume that the contents of .m2/repository can be fetched from the cache.
    - name: Ping pong
      run: |
        echo 'PR to main, branch: ${{ steps.branch_name.outputs.branch }}, commit_id: ${{ steps.commit_id.outputs.sha_short }}'

    - name: Kubeval
      uses: stefanprodan/kube-tools@v1
      with:
        kubectl: 1.22.0
        kustomize: 4.4.1
        helmv3: 3.7.2
        kubeseal: 0.16.0
        kubeval: v0.16.1
        conftest: 0.28.3
        kubeconform: 0.4.12
        command: |
            echo "Run conftest"
            kustomize build k8s/overlays/dev | conftest test -p k8s/base.rego -
            echo "Run kubeval"
            kustomize build k8s/overlays/dev | kubeval --strict
    - name: kube-linter
      uses: stackrox/kube-linter-action@v1.0.4
      with:
        # Directory or file to scan
        directory: k8s/overlays/dev
        # Path to config file
        # config: # optional
        # Output format. Allowed values: sarif, plain, json. Default: "plain"
        # format: # optional, default is plain
        # Filename to store output. File will be overwritten if it exists. Default: "kubelinter.log"
        # output-file: # optional, default is kubelinter.log
        # Version of kube-linter to use. E.g. "0.2.4". Default: "latest"
        # version: # optional, default is latest

